name = "nexrender-serverless"
main = "dist/worker.js"
compatibility_date = "2022-12-27"
workers_dev = true
compatibility_flags = ["durable_object_alarms"]

[build]
command = "npx webpack --mode=production"

[vars]
# NEXRENDER_SECRET = "secret2"
# CLEANUP_INTERVAL = "30000"
# NEXRENDER_PUBLIC_KEY = '''
# '''

[[ d1_databases ]]
binding = "NEXRENDER_D1"
database_name = "Nexrender"
database_id = ""

[durable_objects]
bindings = [
  { name = "DATABASE", class_name = "Database" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Database"]
